### ISSUE TITLE
stay in the same pair after pressing enter

### ISSUE THREAD

**Issue by p00f** [gpanders/nvim-parinfer#4] opened 2021-10-30 05:25 UTC
I understand that nvim-parinfer behaves like the original parinfer but parinfer-rust (and parinfer-rust-mode for emacs) stays in the same pair after pressing enter which is nicer, I don't have to press space many times to get to that point. Could this be added?

parinfer-rust:

https://user-images.githubusercontent.com/36493671/139521418-fae55149-0b9a-4174-88ca-ec92ec5cc719.mp4

nvim-parinfer:

https://user-images.githubusercontent.com/36493671/139521420-c3ae84b2-c9b7-41ef-a3ec-470ee0713cc7.mp4

**Comment by gpanders** [comment] 2021-11-02 16:55
I can't reproduce this. If I use the following test code (`|` represents cursor position):

```fennel
(hello (world (goodbye|)))
```

and press `Return` I get:

```fennel
(hello (world (goodbye
                        |)))
```

Likewise for any of the other trailing parens.

**Comment by p00f** [comment] 2021-11-11 09:13
Maybe it is a problem with my setup, thanks

**Comment by p00f** [comment] 2021-11-16 06:10
Update: It only happens when `g:parinfer_force_balance` is `true`, but when you turn it off this happens:

https://user-images.githubusercontent.com/36493671/141930599-761584a4-e869-4b50-984d-926434d77b4b.mp4

The full code there is
```fennel
(defn- maker [filepath bufnr opts]
  (let [filepath (vim.fn.expand filepath)]
    (: (Job:new {:command "file"
                 :args ["--mime-type" "-b" filepath]
                 :on_exit
                   (fn [j]
                     (let [ft (. (vim.split
                                   (. (j:result) 1)
                                   "/")
                                 1)]
                       (if (or (= "text" ft) (= "inode" ft))
                           (previewers.buffer_previewer_maker filepath bufnr opts)
                           (vim.schedule (fn [] (vim.api.nvim_buf_set_lines bufnr 0 -1 false ["BINARY"]))))))})
```

so the cursor aligns with the J in Job

**Comment by gpanders** [comment] 2021-11-16 15:45
Closed by https://github.com/gpanders/nvim-parinfer/commit/793d6fadb2b751867d30f2b44d856d7f8844e46b

**Closed by gpanders** 2021-11-16 15:45 UTC
