### ISSUE TITLE
Jittery behaviour

### ISSUE THREAD

**Issue by lispyclouds** [gpanders/nvim-parinfer#14] opened 2022-12-16 10:53 UTC
Hello, thanks a lot for making this and I'm a happy user of this!

Just letting you know that I've been seeing this "jittery" behaviour (the whole content jumps) on the UI whenever the parens are matched. I'm not sure if its being caused by this or something in my [config](https://github.com/lispyclouds/dotfiles/tree/main/nvim). I didn't have this issue with parinfer-rust.

Although all the functionality is great, this is just a bit annoying and any help is much appreciated and apologies if this has been reported before!

https://user-images.githubusercontent.com/5615588/208082660-608800f7-adbe-4289-bfae-7402f507fcb0.mov

**Comment by lispyclouds** [comment] 2023-03-19 08:24
Hey @gpanders just dropping by for any pointer on this hopefully? 😄

**Comment by gpanders** [comment] 2023-03-20 14:26
At this point this plugin works well enough for me that I am not highly motivated to do further debugging unless it's an issue I am seeing myself. I would be happy to review PRs that address bugs or add improvements however.

As for this particular issue, it looks like the jitteriness comes from the sign column being redrawn on text changes. As an experiment, could you try setting `signcolumn` to some constant value like `set signcolumn=yes:2` and see if that makes any difference?

**Comment by lispyclouds** [comment] 2023-03-20 14:31
Perfect! That fixes it. Thanks a lot for the hint!

**Comment by gpanders** [comment] 2023-03-20 14:41
I actually can replicate this, and now that I'm looking at it I'd like to come up with a better solution.

**Comment by gpanders** [comment] 2023-03-20 14:45
The issue is that after we invoke the parinfer algorithm we are replacing the entire buffer contents, even if it hasn't changed. This causes the entire sign column (in particular, the git hunk markers in the sign column) to be recalculated. While that is happening the sign column disappears briefly.

A hacky solution would be to temporarily "fix" the sign column by setting the `'signcolumn'` option like I suggested above. Alternatively, I could use `vim.diff` to try and only update the lines in the buffer that actually changed. I have a prototype for this, but not sure yet what side effects this might have.

If you like, you can test drive https://github.com/gpanders/nvim-parinfer/pull/16 and let me know how well that works for you (or if it introduces any regressions).

**Comment by lispyclouds** [comment] 2023-03-20 14:52
[That's](https://github.com/lispyclouds/dotfiles/blob/main/tasks/general/commit.clj) the file i was trying to edit and here are my [dots](https://github.com/lispyclouds/dotfiles) if it helps!

**Comment by gpanders** [comment] 2023-03-20 14:59
Ok that makes sense, in this case the lines being changed are the only lines that have the git hunk markers, so even though we're not replacing the entire buffer, when those few lines get replaced the signs are still being removed and re-added.

**Comment by gpanders** [comment] 2023-03-20 15:07
#16 still helps, though is (clearly) not a sufficient solution. I am actually not sure if there _is_ a general solution to this. I'm assuming you are using gitsigns.nvim. That plugin also attaches to the buffer to receive update events, just like this one, so when nvim-parinfer modifies the buffer, gitsigns also updates the signs.

**Comment by gpanders** [comment] 2023-03-20 15:53
https://github.com/lewis6991/gitsigns.nvim/issues/521 looks to be a related issue.

I'm going to close this when #16 is merged, even though it doesn't completely solve the jitter/flickering, as I don't believe it is possible to fully solve it given the constraints (outside of setting `'signcolumn'` to a fixed width).

**Closed** 2023-04-05 19:38 UTC
